//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _1_DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CarRentEntities : DbContext
    {
        public CarRentEntities()
            : base("name=CarRentEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<branchs_tbl> branchs_tbl { get; set; }
        public virtual DbSet<cars_tbl> cars_tbl { get; set; }
        public virtual DbSet<carsType_tbl> carsType_tbl { get; set; }
        public virtual DbSet<orders_tbl> orders_tbl { get; set; }
        public virtual DbSet<users_tbl> users_tbl { get; set; }
    }
}
