//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _1_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class carsType_tbl
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public carsType_tbl()
        {
            this.cars_tbl = new HashSet<cars_tbl>();
        }
    
        public int CarTypeId { get; set; }
        public string ModelMake { get; set; }
        public string Model { get; set; }
        public string ModelName { get; set; }
        public string ModelYear { get; set; }
        public string ModelBody { get; set; }
        public Nullable<int> ModelWeightKg { get; set; }
        public Nullable<int> ModelDoors { get; set; }
        public string Gear { get; set; }
        public string BranchesCar { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cars_tbl> cars_tbl { get; set; }
    }
}
