//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _1_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class cars_tbl
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public cars_tbl()
        {
            this.orders_tbl = new HashSet<orders_tbl>();
        }
    
        public int CarId { get; set; }
        public int CarTypeId { get; set; }
        public int ActuallyKm { get; set; }
        public string Picture { get; set; }
        public Nullable<bool> ProperToBeRent { get; set; }
        public Nullable<bool> AvaibleToBeRent { get; set; }
        public int DayPrice { get; set; }
        public int DayDelayPrice { get; set; }
        public Nullable<int> PlateNumber { get; set; }
        public Nullable<int> BranchId { get; set; }
    
        public virtual branchs_tbl branchs_tbl { get; set; }
        public virtual carsType_tbl carsType_tbl { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<orders_tbl> orders_tbl { get; set; }
    }
}
