//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _1_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class orders_tbl
    {
        public int OrderId { get; set; }
        public System.DateTime PickUpDate { get; set; }
        public System.DateTime ReturnDate { get; set; }
        public System.DateTime ActuallReturnDate { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> CarId { get; set; }
    
        public virtual cars_tbl cars_tbl { get; set; }
        public virtual users_tbl users_tbl { get; set; }
    }
}
