//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _1_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class users_tbl
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public users_tbl()
        {
            this.orders_tbl = new HashSet<orders_tbl>();
        }
    
        public int UserId { get; set; }
        public string FullName { get; set; }
        public int Identity { get; set; }
        public string UserName { get; set; }
        public Nullable<System.DateTime> BirthDay { get; set; }
        public string Gender { get; set; }
        public string Email { get; set; }
        public string Passwords { get; set; }
        public string Picture { get; set; }
        public string Rank { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<orders_tbl> orders_tbl { get; set; }
    }
}
